io.write("Installing relay system")
shell.run('wget https://raw.githubusercontent.com/Minejerikisme/Computercraftnetworking/main/startup.lua ')
shell.run('wget https://raw.githubusercontent.com/Minejerikisme/Computercraftnetworking/main/standard.lua ')
shell.run('wget hhttps://raw.githubusercontent.com/Minejerikisme/Computercraftnetworking/main/updater.lua ')
shell.run('wget https://raw.githubusercontent.com/Minejerikisme/Computercraftnetworking/main/sha.lua ')
fs.makeDir("data")
shell.run('cd data')
shell.run('wget https://raw.githubusercontent.com/Minejerikisme/Computercraftnetworking/main/data/cc.md ')
shell.run('wget https://raw.githubusercontent.com/Minejerikisme/Computercraftnetworking/main/data/rc.md ')
shell.run('wget https://raw.githubusercontent.com/Minejerikisme/Computercraftnetworking/main/data/rn.md ')
os.reboot()