io.write("Installing relay system")
shell.run('wget("https://raw.githubusercontent.com/Minejerikisme/Computercraftnetworking/main/startup.lua", "startup.lua")')
shell.run('wget("https://raw.githubusercontent.com/Minejerikisme/Computercraftnetworking/main/standard.lua", "standard.lua")')
shell.run('wget("hhttps://raw.githubusercontent.com/Minejerikisme/Computercraftnetworking/main/updater.lua", "updater.lua")')
shell.run('wget("https://raw.githubusercontent.com/Minejerikisme/Computercraftnetworking/main/sha.lua", "sha.lua")')
fs.makeDir("data")
shell.run('cd data')
shell.run('touch cc.md')
shell.run('touch rc.md')
shell.run('touch rn.md')
os.reboot()