io.write("Installing relay system")
shell.run('wget https://raw.githubusercontent.com/Minejerikisme/Computercraftnetworking/main/RELAY%20MOMENT/startup.lua ')
shell.run('wget https://raw.githubusercontent.com/Minejerikisme/Computercraftnetworking/main/RELAY%20MOMENT/standard.lua ')
shell.run('wget https://raw.githubusercontent.com/Minejerikisme/Computercraftnetworking/main/RELAY%20MOMENT/updater.lua ')
shell.run('wget https://raw.githubusercontent.com/Minejerikisme/Computercraftnetworking/main/RELAY%20MOMENT/sha.lua ')
fs.makeDir("data")
shell.run('cd data')
shell.run('wget https://raw.githubusercontent.com/Minejerikisme/Computercraftnetworking/main/RELAY%20MOMENT/data/cc.md ')
shell.run('wget https://raw.githubusercontent.com/Minejerikisme/Computercraftnetworking/main/RELAY%20MOMENT/data/rc.md ')
shell.run('wget https://raw.githubusercontent.com/Minejerikisme/Computercraftnetworking/main/RELAY%20MOMENT/data/rn.md ')
os.reboot()